/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/jwt/create': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log in: returns the access token and sets the refresh/CSRF cookies */
    post: operations['AuthController_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/jwt/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Rotate tokens using the refresh cookie (requires X-CSRF-Token header) */
    post: operations['AuthController_refresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/jwt/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Log out: clears the refresh/CSRF cookies */
    post: operations['AuthController_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get the current authenticated user */
    get: operations['UsersController_me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update the current user profile */
    patch: operations['UsersController_updateMe']
    trace?: never
  }
  '/api/auth/me/password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Change the current user password */
    post: operations['UsersController_changePassword']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/contacts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List other users (to start chats / build groups) */
    get: operations['UsersController_contacts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all users (admin only) */
    get: operations['UsersController_list']
    put?: never
    /** Create a user (admin only) */
    post: operations['UsersController_create']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete a user (admin only) */
    delete: operations['UsersController_remove']
    options?: never
    head?: never
    /** Update a user (admin only) */
    patch: operations['UsersController_update']
    trace?: never
  }
  '/api/auth/users/{id}/role': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Change a user role, e.g. promote to admin (admin only) */
    patch: operations['UsersController_changeRole']
    trace?: never
  }
  '/api/chat/conversations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List conversations of the current user */
    get: operations['ChatController_listConversations']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/chat/conversations/group': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a group conversation */
    post: operations['ChatController_createGroup']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/chat/conversations/direct': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Open (or create) a 1:1 conversation with another user */
    post: operations['ChatController_createDirect']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/chat/conversations/{id}/messages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get messages of a conversation (newest-cursor pagination) */
    get: operations['ChatController_getMessages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/chat/messages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Send a message over REST (also broadcast to live sockets) */
    post: operations['ChatController_sendMessage']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Service and database health check */
    get: operations['HealthController_check[0]']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Service and database health check */
    get: operations['HealthController_check[1]']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    LoginDto: {
      /** @example admin */
      username: string
      /** @example StrongPass123 */
      password: string
    }
    AccessTokenDto: {
      /** @description Short-lived JWT access token (store in memory only) */
      access: string
    }
    /** @enum {string} */
    UserRole: 'ADMIN' | 'USER'
    /** @enum {string} */
    UserLanguage: 'en' | 'ru'
    UserDto: {
      /** Format: uuid */
      id: string
      username: string
      email: string
      firstName: string
      lastName: string
      role: components['schemas']['UserRole']
      language: components['schemas']['UserLanguage']
    }
    UpdateProfileDto: {
      language: components['schemas']['UserLanguage']
    }
    ChangePasswordDto: {
      currentPassword: string
      newPassword: string
    }
    MessageResponseDto: {
      detail: string
    }
    ContactDto: {
      /** Format: uuid */
      id: string
      username: string
      firstName: string
      lastName: string
    }
    CreateUserDto: {
      /** @example jdoe */
      username: string
      /**
       * Format: email
       * @example jdoe@example.com
       */
      email?: string
      /** @example StrongPass123 */
      password: string
      /** @default USER */
      role: components['schemas']['UserRole']
      firstName?: string
      lastName?: string
    }
    UpdateUserDto: {
      /** @example jdoe */
      username?: string
      /**
       * Format: email
       * @example jdoe@example.com
       */
      email?: string
      firstName?: string
      lastName?: string
      role?: components['schemas']['UserRole']
      language?: components['schemas']['UserLanguage']
    }
    UpdateRoleDto: {
      role: components['schemas']['UserRole']
    }
    /** @enum {string} */
    ConversationType: 'direct' | 'group'
    ConversationParticipantDto: {
      /** Format: uuid */
      id: string
      username: string
      firstName: string
      lastName: string
    }
    MessageDto: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      conversationId: string
      /** Format: uuid */
      senderId: string
      content: string
      /** Format: date-time */
      createdAt: string
    }
    ConversationDto: {
      /** Format: uuid */
      id: string
      type: components['schemas']['ConversationType']
      title: string | null
      participants: components['schemas']['ConversationParticipantDto'][]
      lastMessage?: components['schemas']['MessageDto'] | null
      /** Format: date-time */
      updatedAt: string
    }
    CreateGroupDto: {
      /** @example Project Falcon */
      title: string
      /**
       * @description User ids to add as members (the creator is added automatically)
       * @example []
       */
      memberIds: string[]
    }
    CreateDirectDto: {
      /**
       * Format: uuid
       * @description The other participant of the 1:1 conversation
       */
      userId: string
    }
    SendMessageDto: {
      /** Format: uuid */
      conversationId: string
      content: string
    }
    HealthDto: {
      /** @example ok */
      status: string
      /** @example ok */
      database: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  AuthController_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccessTokenDto']
        }
      }
    }
  }
  AuthController_refresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AccessTokenDto']
        }
      }
    }
  }
  AuthController_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserDto']
        }
      }
    }
  }
  UsersController_updateMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProfileDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserDto']
        }
      }
    }
  }
  UsersController_changePassword: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageResponseDto']
        }
      }
    }
  }
  UsersController_contacts: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ContactDto'][]
        }
      }
    }
  }
  UsersController_list: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserDto'][]
        }
      }
    }
  }
  UsersController_create: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserDto']
        }
      }
    }
  }
  UsersController_remove: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UsersController_update: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserDto']
        }
      }
    }
  }
  UsersController_changeRole: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateRoleDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserDto']
        }
      }
    }
  }
  ChatController_listConversations: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationDto'][]
        }
      }
    }
  }
  ChatController_createGroup: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGroupDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationDto']
        }
      }
    }
  }
  ChatController_createDirect: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDirectDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ConversationDto']
        }
      }
    }
  }
  ChatController_getMessages: {
    parameters: {
      query?: {
        limit?: number
        /** @description Return messages created strictly before this message id (cursor pagination) */
        before?: string
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageDto'][]
        }
      }
    }
  }
  ChatController_sendMessage: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SendMessageDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MessageDto']
        }
      }
    }
  }
  'HealthController_check[0]': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthDto']
        }
      }
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthDto']
        }
      }
    }
  }
  'HealthController_check[1]': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthDto']
        }
      }
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthDto']
        }
      }
    }
  }
}
